#!/bin/sh

function cpp() {
echo \
'#include <iostream>
using namespace std;

void main () {
    cout << "Hello World!" << endl;
}
' > $APP.cpp
}

function cmakefile() {
echo \
'project('$APP' CXX)

if (MSVC)
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /W4 /EHsc")
else()
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wall")
endif()

cmake_minimum_required(VERSION 3.17)

add_executable(
    '$APP'
    ./src/'$APP'.cpp
)

set_property(
    TARGET '$APP'
    PROPERTY CXX_STANDARD 14
)

target_include_directories(
    '$APP' PRIVATE ../src
)' > CMakeLists.txt
}

export APP=${PWD##*/}

mkdir -p src
pushd src
cpp
popd

cmakefile

mkdir -p build
pushd build
cmake ..
popd
