#!/bin/sh

# TODO
# generate appsettings files for proxies
# adjust production website urls (perhaps)

set -e

function create_web_site_script() {

    if ! [ -e $iis_setup_script ]; then
        echo "- creating iis site setup script: $iis_setup_script"
    else
        echo "- appending to iis site setup script: $iis_setup_script"
    fi

    if [ -z "$solution_env_host_ip" ]; then
        export solution_env_host_ip="127.0.0.1"
        echo "  (solution_env_host_ip not set, using $solution_env_host_ip)"
    fi

    if [ -z "$solution_env_apppool_identity" ]; then
        export solution_env_apppool_identity="LocalSystem"
        echo $app_vs_project_name: solution_env_apppool_identity not set, using $solution_env_apppool_identity
    fi

    if [ "$application_type" == "Ui" ]; then
        export webapp_sub_domain=$solution_environment-$application_name
    else
        export webapp_sub_domain=$solution_environment-$application_type-$application_name
    fi

    export webapp_site_name=$solution_environment-$application_name-$application_type.$solution_domain
    export webapp_host_name=$webapp_sub_domain.$solution_domain
    export webapp_physical_path=$solution_iis_physical_path_root/$app_vs_project_name
    export webapp_physical_path_dos=$solution_iis_physical_path_root_dos\\$app_vs_project_name

    export webapp_site_bindings=$webapp_host_name

    echo $app_cmd delete site $webapp_site_name >> $iis_setup_script
    echo $app_cmd delete apppool $webapp_site_name >> $iis_setup_script

    echo $app_cmd add apppool /name:"$webapp_site_name" /managedRuntimeVersion:"" -processModel.identityType:$solution_env_apppool_identity >> $iis_setup_script
    echo $app_cmd add site /name:"$webapp_site_name" /site.name:"$webapp_site_name" /bindings:"http://$webapp_site_bindings:80" /physicalPath:"$webapp_physical_path_dos" >> $iis_setup_script
    # echo $app_cmd add site /name:"$webapp_site_name" /site.name:"$webapp_site_name" /+bindings.[protocol="https",bindinginformation="*443$webapp_site_bindings"] >> $iis_setup_script
    echo $app_cmd set app "$webapp_site_name/" /applicationPool:"$webapp_site_name" >> $iis_setup_script
    echo $app_cmd start apppool /apppool.name:"$webapp_site_name" >> $iis_setup_script
    echo '' >> $iis_setup_script
}

function create_hosts_section() {

    if ! [ -e $hosts_file ]; then
        echo "- creating hosts file section: $hosts_file"
        echo "# BEGIN Solution: $solution_folder, Environment: $solution_environment" > $hosts_file
        echo "" >> $hosts_file
    else
        echo "- appending to hosts file section: $hosts_file"
    fi

    export info="$application_name, $solution_environment, $application_type"

    echo "# $info" >> $hosts_file

    echo "# Site name:        $webapp_site_name" >> $hosts_file
    echo "# Application pool: $webapp_site_name" >> $hosts_file
    echo "# Physical path:    $webapp_physical_path" >> $hosts_file
    echo "$solution_env_host_ip $webapp_host_name" >> $hosts_file

    echo '' >> $hosts_file
}

function create_deployment_script() {

    if ! [ -e $iis_deploy_script ]; then
        echo "- creating deployment script: $iis_deploy_script"
        echo "#!/bin/sh" >> $iis_deploy_script
        echo '' >> $iis_deploy_script
        echo "set -e" >> $iis_deploy_script
        echo '' >> $iis_deploy_script
    else
        echo "- appending to deployment script: $iis_deploy_script"
    fi

    artifacts_folder=bin/Debug/netcoreapp3.1/publish

    echo "pushd $app_vs_project_name" >> $iis_deploy_script
    echo "dotnet publish" >> $iis_deploy_script
    echo "mkdir -p $webapp_physical_path" >> $iis_deploy_script
    echo "rm -rf $webapp_physical_path/*" >> $iis_deploy_script
    echo "cp -R $artifacts_folder/* $webapp_physical_path" >> $iis_deploy_script
    echo "popd" >> $iis_deploy_script

    echo '' >> $iis_deploy_script
}

# Entry point

if [ -z "$1" ]; then
    echo USAGE: "$0 clean/create solution_folder application_name Api/Ui"
    echo $0 ERROR: solution_folder not set
    exit 1
fi

export mode=

if [ $1 = "clean" ]; then
    export mode=clean
fi

if [ $1 = "create" ]; then
    export mode=create
fi

if [ -z "$solution_environment" ]; then
    export solution_environment=$ASPNETCORE_ENVIRONMENT
    echo solution_environment not set, using ASPNETCORE_ENVIRONMENT: $ASPNETCORE_ENVIRONMENT
fi

export iis_setup_script=./scripts/iis-setup-$solution_environment.bat
export solution_iis_physical_path_root_dos=$SYSTEMDRIVE\\inetpub\\$solution_environment-$solution_folder.$solution_domain
export solution_iis_physical_path_root=/C/inetpub/$solution_environment-$solution_folder.$solution_domain
export iis_deploy_script=./scripts/iis-deploy-$solution_environment
export hosts_file=./scripts/hosts_$solution_environment

if [ $mode == "clean" ]; then
    echo "cleaning $solution_environment scripts..."
    rm -f $iis_setup_script
    rm -f $iis_deploy_script
    rm -f $hosts_file
    exit 0
fi

if [ -z $mode ]; then
    echo USAGE: "$0 clean/create solution_folder application_name Api/Ui"
    echo $0 ERROR: unknown mode: $1
    exit 1
fi

if [ -z "$2" ]; then
    echo USAGE: "$0 clean/create solution_folder application_name Api/Ui"
    echo $0 ERROR: solution_folder not set
    exit 1
fi

if [ -z "$3" ]; then
    echo USAGE: "$0 clean/create solution_folder application_name Api/Ui"
    echo $0 ERROR: application_name not set
    exit 1
fi

if [ -z "$4" ]; then
    echo USAGE: "$0 clean/create solution_folder application_name Api/Ui"
    echo $0 ERROR: application_type not set
    exit 1
fi

export solution_folder=$2
export application_name=$3
export application_type=$4

export app_vs_project_name=$application_name$application_type

echo Solution: $solution_folder - generating scripts for application: $app_vs_project_name in environment: $solution_environment

if [ -z "$iis_setup_script" ]; then
    echo $0 ERROR: iis_setup_script not set
    exit 1
fi

if [ -z "$hosts_file" ]; then
    echo $0 ERROR: hosts_file not set
    exit 1
fi

if [ -z "$iis_deploy_script" ]; then
    echo $0 ERROR: iis_deploy_script not set
    exit 1
fi

if [ -z "$application_name" ]; then
    echo $0 ERROR: application_name not set
    exit 1
fi

if [ -z "$solution_domain" ]; then
    echo $0 ERROR: solution_domain not set
    exit 1
fi

if [ -z "$solution_environment" ]; then
    echo $0 ERROR: solution_environment not set
    exit 1
fi

if [ -z "$solution_iis_physical_path_root" ]; then
    echo $0 ERROR: solution_iis_physical_path_root not set
    exit 1
fi

if [ -z "$application_type" ]; then
    echo $0 ERROR: application_type not set
    exit 1
fi

if [ -z "$app_vs_project_name" ]; then
    echo $0 ERROR: app_vs_project_name not set
    exit 1
fi

export app_cmd=$WINDIR\\system32\\inetsrv\\appcmd.exe

create_web_site_script
create_deployment_script
create_hosts_section

echo ""