#!/bin/bash
filepath=$(realpath $1)

if [ ! -f "$filepath" ]; then
    echo "ERROR: $filepath not found"
    exit -1
fi

extension="${filepath##*.}"
name="${filepath%.*}"
echo full name and path $filepath
echo file name $name
echo file extension $extension

PF86COMMON="C:\\Program Files (x86)\\Common Files"

function launch_app {
    echo launching $app $filepath
    "$app" "$filepath"
}

function set_app_vs {
    app="$PF86COMMON\\Microsoft Shared\\MSEnv\\VSLauncher.exe"
}

case $extension in
    sln)
    set_app_vs
    launch_app $filepath
    ;;
    csproj)
    launch_app $filepath
    ;;
    *)
    echo unhandled file extension: "$extension"
esac