#!/bin/bash

if [ -f build.sbt ]; then
    echo build.sbt found...
    exit 0
fi

echo build.sbt not found, initializing

mkdir -p src/{main,test}/{java,resources,scala}
mkdir lib project target

# create an initial build.sbt file
echo 'name := "MyProject"
version := "1.0"
scalaVersion := "2.10.0"' > build.sbt